git clone https://github.com/vedderb/rise_sdvp.git
git clone https://github.com/vedderb/bldc-bootloader.git
git clone https://github.com/vedderb/bldc_uart_comm_stm32f4_discovery.git
git clone https://github.com/vedderb/bldc.git
git clone https://github.com/vedderb/vesc_tool.git
git clone https://github.com/vedderb/svm_sim.git
git clone https://github.com/vedderb/summon-arm-toolchain.git
git clone https://github.com/vedderb/nrf51_vesc.git
git clone https://github.com/vedderb/bldc-tool.git
git clone https://github.com/vedderb/nunchuk_mod.git
git clone https://github.com/vedderb/bldc-hardware.git
git clone https://github.com/vedderb/bldc-logger.git
git clone https://github.com/vedderb/QuadcopterSystem.git
git clone https://github.com/vedderb/nunchuk_rf_hw.git
git clone https://github.com/vedderb/FaultCheck_QuickCheck.git
git clone https://github.com/vedderb/CapPCB.git
git clone https://github.com/vedderb/SparkSwitch.git
git clone https://github.com/vedderb/udp-uart-bridge.git
git clone https://github.com/vedderb/FaultCheck_ScalaCheck.git
git clone https://github.com/vedderb/nrf24l01plus_stm32f100_chibios.git
git clone https://github.com/vedderb/rfboard-chibios.git
git clone https://github.com/vedderb/contiki.git
